// <auto-generated />
using System;
using InvestmentTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InvestmentTrackerDbContext))]
    [Migration("20260908231723_PortfolioTrades")]
    partial class PortfolioTrades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("AssetTypeId")
                        .HasColumnType("int");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId");

                    b.HasIndex("AssetTypeId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("SectorId");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Asset", (string)null);
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.AssetCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssetCategory", (string)null);
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.AssetType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("AssetType", (string)null);
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.CategoryAllocationTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetPercentage")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("Id");

                    b.HasIndex("AssetCategoryId");

                    b.HasIndex("PortfolioId", "AssetCategoryId")
                        .IsUnique();

                    b.ToTable("CategoryAllocationTarget", null, t =>
                        {
                            t.HasCheckConstraint("CK_CategoryAllocationTarget_Percentage", "[TargetPercentage] >= 0 AND [TargetPercentage] <= 1");
                        });
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currency", (string)null);
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.ExchangeRate", b =>
                {
                    b.Property<string>("BaseCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("QuoteCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate")
                        .HasPrecision(28, 12)
                        .HasColumnType("decimal(28,12)");

                    b.Property<DateOnly>("RateDate")
                        .HasColumnType("date");

                    b.HasKey("BaseCode", "QuoteCode");

                    b.ToTable("ExchangeRate", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExchangeRate_Positive", "[Rate] > 0");
                        });
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.ExternalAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date");

                    b.Property<decimal>("Value")
                        .IsConcurrencyToken()
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("PortfolioId");

                    b.ToTable("ExternalAsset", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExternalAsset_Value", "[Value] >= 0");
                        });
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseCurrencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BaseCurrencyId");

                    b.ToTable("Portfolio", (string)null);
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.PortfolioAsset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentValue")
                        .IsConcurrencyToken()
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("Income")
                        .IsConcurrencyToken()
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("InvestedAmount")
                        .IsConcurrencyToken()
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .IsConcurrencyToken()
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<DateOnly>("UpdatedOn")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("PortfolioId", "AssetId")
                        .IsUnique();

                    b.ToTable("PortfolioAsset", null, t =>
                        {
                            t.HasCheckConstraint("CK_PortfolioAsset_NonNegative", "[Quantity] >= 0 AND [InvestedAmount] >= 0 AND [CurrentValue] >= 0 AND [Income] >= 0");
                        });
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.PortfolioCashFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal?>("BaseAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<int?>("TradeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyId");

                    b.HasIndex("TradeId")
                        .IsUnique()
                        .HasFilter("[TradeId] IS NOT NULL");

                    b.HasIndex("PortfolioId", "Date");

                    b.ToTable("PortfolioCashFlow", null, t =>
                        {
                            t.HasCheckConstraint("CK_PortfolioCashFlow_Kind", "[Kind] IN ('contribution', 'withdrawal')");

                            t.HasCheckConstraint("CK_PortfolioCashFlow_Values", "[Amount] > 0 AND ([BaseAmount] IS NULL OR [BaseAmount] > 0)");
                        });
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.PortfolioSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DashboardJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExternalValue")
                        .HasPrecision(38, 4)
                        .HasColumnType("decimal(38,4)");

                    b.Property<bool>("HasFallbackRates")
                        .HasColumnType("bit");

                    b.Property<bool>("HasStaleRates")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("Month")
                        .HasColumnType("date");

                    b.Property<int>("PayloadVersion")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("PortfolioValue")
                        .HasPrecision(38, 4)
                        .HasColumnType("decimal(38,4)");

                    b.Property<DateOnly>("SnapshotDate")
                        .HasColumnType("date");

                    b.Property<decimal>("TotalIncome")
                        .HasPrecision(38, 4)
                        .HasColumnType("decimal(38,4)");

                    b.Property<decimal>("TotalWealth")
                        .HasPrecision(38, 4)
                        .HasColumnType("decimal(38,4)");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId", "Month")
                        .IsUnique();

                    b.ToTable("PortfolioSnapshot", null, t =>
                        {
                            t.HasCheckConstraint("CK_PortfolioSnapshot_Json", "ISJSON([DashboardJson]) = 1");

                            t.HasCheckConstraint("CK_PortfolioSnapshot_Month", "DAY([Month]) = 1 AND YEAR([Month]) = YEAR([SnapshotDate]) AND MONTH([Month]) = MONTH([SnapshotDate])");

                            t.HasCheckConstraint("CK_PortfolioSnapshot_Values", "[PortfolioValue] >= 0 AND [ExternalValue] >= 0 AND [TotalWealth] >= 0 AND [TotalIncome] >= 0");
                        });
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.PortfolioTrade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("CashAssetId")
                        .HasColumnType("int");

                    b.Property<string>("CashAssetName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<decimal>("RemainingCost")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(19, 6)
                        .HasColumnType("decimal(19,6)");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RequestedBaseAmount")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("CashAssetId");

                    b.HasIndex("PortfolioId", "Date");

                    b.HasIndex("PortfolioId", "RequestId")
                        .IsUnique();

                    b.ToTable("PortfolioTrade", null, t =>
                        {
                            t.HasCheckConstraint("CK_PortfolioTrade_Kind", "[Kind] IN ('buy', 'sell')");

                            t.HasCheckConstraint("CK_PortfolioTrade_Values", "[Quantity] > 0 AND [UnitPrice] > 0 AND [Amount] > 0 AND [RemainingQuantity] >= 0 AND [RemainingCost] >= 0");
                        });
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sector", (string)null);
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.SectorAllocationTarget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<int>("SectorId")
                        .HasColumnType("int");

                    b.Property<decimal>("TargetPercentage")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.HasKey("Id");

                    b.HasIndex("SectorId");

                    b.HasIndex("PortfolioId", "SectorId")
                        .IsUnique();

                    b.ToTable("SectorAllocationTarget", null, t =>
                        {
                            t.HasCheckConstraint("CK_SectorAllocationTarget_Percentage", "[TargetPercentage] >= 0 AND [TargetPercentage] <= 1");
                        });
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.Asset", b =>
                {
                    b.HasOne("InvestmentTracker.Domain.Entities.AssetCategory", "AssetCategory")
                        .WithMany("Assets")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentTracker.Domain.Entities.AssetType", "AssetType")
                        .WithMany("Assets")
                        .HasForeignKey("AssetTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentTracker.Domain.Entities.Country", "Country")
                        .WithMany("Assets")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentTracker.Domain.Entities.Currency", "Currency")
                        .WithMany("Assets")
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentTracker.Domain.Entities.Sector", "Sector")
                        .WithMany("Assets")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetCategory");

                    b.Navigation("AssetType");

                    b.Navigation("Country");

                    b.Navigation("Currency");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.CategoryAllocationTarget", b =>
                {
                    b.HasOne("InvestmentTracker.Domain.Entities.AssetCategory", "AssetCategory")
                        .WithMany("AllocationTargets")
                        .HasForeignKey("AssetCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentTracker.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("CategoryAllocationTargets")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssetCategory");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.ExternalAsset", b =>
                {
                    b.HasOne("InvestmentTracker.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentTracker.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Currency");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.Portfolio", b =>
                {
                    b.HasOne("InvestmentTracker.Domain.Entities.Currency", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BaseCurrency");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.PortfolioAsset", b =>
                {
                    b.HasOne("InvestmentTracker.Domain.Entities.Asset", "Asset")
                        .WithMany("PortfolioAssets")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentTracker.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("PortfolioAssets")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.PortfolioCashFlow", b =>
                {
                    b.HasOne("InvestmentTracker.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentTracker.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentTracker.Domain.Entities.PortfolioTrade", "Trade")
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Currency");

                    b.Navigation("Portfolio");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.PortfolioSnapshot", b =>
                {
                    b.HasOne("InvestmentTracker.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.PortfolioTrade", b =>
                {
                    b.HasOne("InvestmentTracker.Domain.Entities.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentTracker.Domain.Entities.ExternalAsset", null)
                        .WithMany()
                        .HasForeignKey("CashAssetId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvestmentTracker.Domain.Entities.Portfolio", null)
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.SectorAllocationTarget", b =>
                {
                    b.HasOne("InvestmentTracker.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("SectorAllocationTargets")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InvestmentTracker.Domain.Entities.Sector", "Sector")
                        .WithMany("AllocationTargets")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Portfolio");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.Asset", b =>
                {
                    b.Navigation("PortfolioAssets");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.AssetCategory", b =>
                {
                    b.Navigation("AllocationTargets");

                    b.Navigation("Assets");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.AssetType", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.Country", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.Currency", b =>
                {
                    b.Navigation("Assets");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("CategoryAllocationTargets");

                    b.Navigation("PortfolioAssets");

                    b.Navigation("SectorAllocationTargets");
                });

            modelBuilder.Entity("InvestmentTracker.Domain.Entities.Sector", b =>
                {
                    b.Navigation("AllocationTargets");

                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
